### ISSUE TITLE
prevent Print Screen button doesn't work

### ISSUE THREAD

**Issue by MaksimKarpets** [bmiit145/secure-web#1]
Here's code that fix it. You can just replace it, or adjust as you need
Basically keydown event doesn't fire for this button

The idea is to clear clipboard data

```javascript
if (disablePrintScreen) {
    document.addEventListener('keyup', (event) => {
      if (event.key === 'PrintScreen') {
        navigator.clipboard.writeText('')
        overlayScreen()
      }
    })
  }
```

**Comment by bmiit145** [comment]
I just wanted to drop you a quick note to say thank you for the suggestion you made. Your input means a lot to me, and I really appreciate you taking the time to share your ideas.

Your suggestion is going to make a real difference in npm Package, and I'm grateful for your contribution. It's great to have someone like you who's willing to jump in and help out.

Thanks again for your valuable input. If you have any more ideas or feedback in the future, please feel free to share them. Your involvement is awesome!
